spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coding_bat
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    basename: validation-messages
debug: true
server:
  port: 8050
